version: "3"
networks:
  backend:
    driver: bridge
services:
  config-srv:
    build:
      context: ./config-srv
    environment:
      - MICRO_REGISTRY=${MICRO_REGISTRY}
      - MICRO_REGISTRY_ADDRESS=${MICRO_REGISTRY_ADDRESS}
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - backend
  admin-api:
    build:
      context: ./admin-api
    environment:
      - MICRO_REGISTRY=${MICRO_REGISTRY}
      - MICRO_REGISTRY_ADDRESS=${MICRO_REGISTRY_ADDRESS}
    networks:
      - backend
  agent-api:
    build:
      context: ./agent-api
    environment:
      - MICRO_REGISTRY=${MICRO_REGISTRY}
      - MICRO_REGISTRY_ADDRESS=${MICRO_REGISTRY_ADDRESS}
    networks:
      - backend
  micro:
    build:
      context: ./micro
    environment:
      - MICRO_REGISTRY=${MICRO_REGISTRY}
      - MICRO_REGISTRY_ADDRESS=${MICRO_REGISTRY_ADDRESS}
    networks:
      - backend
    ports:
      - 8080:8080



